name: "Bitwarden Secrets Manager GitHub Action"
description: "GitHub action for retrieving secrets from Bitwarden Secrets Manager"
author: "Bitwarden"

branding:
  icon: "unlock"
  color: "blue"

inputs:
  access_token:
    description: "The machine account access token for retrieving secrets"
    required: true
  secrets:
    description: "One or more secret Ids to retrieve and the corresponding GitHub environment variable name to set"
    required: true
  cloud_region:
    description: "(Optional) The Bitwarden server region to use if cloud-hosted service is used. Either 'us' or 'eu'"
    required: false
    default: "us"
  base_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com"
    required: false
    default: ""
  identity_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com/identity"
    required: false
    default: ""
  api_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com/api"
    required: false
    default: ""
  set_env:
    description: "(Optional) Set the secrets as environment variables. Defaults to true"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Run Action
      run: ./entrypoint.sh
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        SM_ACCESS_TOKEN: ${{ inputs.access_token }}
        SM_CLOUD_REGION: ${{ inputs.cloud_region }}
        SM_SECRETS: ${{ inputs.secrets }}
        SM_BASE_URL: ${{ inputs.base_url }}
        SM_IDENTITY_URL: ${{ inputs.identity_url }}
        SM_API_URL: ${{ inputs.api_url }}
        SM_SET_ENV: ${{ inputs.set_env }}
