name: "Bitwarden Secrets Manager GitHub Action"
description: "GitHub action for retrieving secrets from Bitwarden Secrets Manager"
author: "Bitwarden"

branding:
  icon: "unlock"
  color: "blue"

inputs:
  access_token:
    description: "The machine account access token for retrieving secrets"
    required: true
  secrets:
    description: "One or more secret Ids to retrieve and the corresponding GitHub environment variable name to set"
    required: true
  cloud_region:
    description: "(Optional) The Bitwarden server region to use if cloud-hosted service is used. Either 'us' or 'eu'"
    required: false
  base_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com"
    required: false
    default: ""
  identity_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com/identity"
    required: false
    default: ""
  api_url:
    description: "(Optional) For self-hosted bitwarden instances provide your https://your.domain.com/api"
    required: false
    default: ""
  set_env:
    description: "(Optional) Set the secrets as environment variables. Defaults to true"
    required: false
    default: "true"

runs:
  using: "node20"
  main: "index.js"
